// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6E2vwwuGMhYMPdJy0ejXwQIwl4CJ-Mow',
    appId: '1:224473311778:web:f280f6b3a519d1c5b2387b',
    messagingSenderId: '224473311778',
    projectId: 'medconnect-85d3b',
    authDomain: 'medconnect-85d3b.firebaseapp.com',
    storageBucket: 'medconnect-85d3b.appspot.com',
    measurementId: 'G-30JHSB66FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_bCzLENPZxixTROIVZ4rvT0ZRr_pAgC0',
    appId: '1:224473311778:android:ede4794c6f4c4244b2387b',
    messagingSenderId: '224473311778',
    projectId: 'medconnect-85d3b',
    storageBucket: 'medconnect-85d3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsMn3v5w_XDRdpITKUIaBld5N69cbfDog',
    appId: '1:224473311778:ios:69204106941692a9b2387b',
    messagingSenderId: '224473311778',
    projectId: 'medconnect-85d3b',
    storageBucket: 'medconnect-85d3b.appspot.com',
    androidClientId: '224473311778-b03oef3gaq2gnno9clmtv496re7m4asu.apps.googleusercontent.com',
    iosClientId: '224473311778-e3sq402icp2fl7m5i9liitnngf4ic9uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.medConnect',
  );
}
